# This rule is not used by the project db-backup-operator-fork itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the backupschema.jkops.me.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: db-backup-operator-fork
    app.kubernetes.io/managed-by: kustomize
  name: backupdatabaseschema-editor-role
rules:
- apiGroups:
  - backupschema.jkops.me
  resources:
  - backupdatabaseschemas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backupschema.jkops.me
  resources:
  - backupdatabaseschemas/status
  verbs:
  - get
