# This rule is not used by the project db-backup-operator-fork itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over backupschema.jkops.me.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: db-backup-operator-fork
    app.kubernetes.io/managed-by: kustomize
  name: backupdatabaseschema-admin-role
rules:
- apiGroups:
  - backupschema.jkops.me
  resources:
  - backupdatabaseschemas
  verbs:
  - '*'
- apiGroups:
  - backupschema.jkops.me
  resources:
  - backupdatabaseschemas/status
  verbs:
  - get
